version: '3.7'

services:
  back-end-one:
    build:
      context: ./back-end-session
    image: java-meetup-back-end-session
    container_name: java-meetup-back-end-session-one
    restart: always
  back-end-two:
    build:
      context: ./back-end-session
    image: java-meetup-back-end-session
    container_name: java-meetup-back-end-session-two
    restart: always
  back-end-three:
    build:
      context: ./back-end-session
    image: java-meetup-back-end-session
    container_name: java-meetup-back-end-session-three
    restart: always

  front-end:
    build:
      context: ./front-end
      dockerfile: dockerfiles/session/Dockerfile
    image: java-meetup-front-end-session
    container_name: java-meetup-front-end-session
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - back-end-one
      - back-end-two
      - back-end-three
