---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup
  jpa:
    hibernate:
      ddl-auto: update
secret_key: r+W5pErSHJPMkAGsLzMb5j884ARYQ8AmT25vSN8C0iz2ntIu/cP7domeKpRlt2qMwLcZfqx4A94BTQ6UTD2MVg==
csrf:
  enable_check: true
  target: "http://localhost/"

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup_test
  jpa:
    hibernate:
      ddl-auto: create-drop
