---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup_test
  jpa:
    hibernate:
      ddl-auto: create-drop
