---

spring:
  datasource:
    url: "jdbc:h2:file:./db"
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret_key: r+W5pErSHJPMkAGsLzMb5j884ARYQ8AmT25vSN8C0iz2ntIu/cP7domeKpRlt2qMwLcZfqx4A94BTQ6UTD2MVg==
  short_expiration_in_seconds: 60
  long_expiration_in_seconds: 1800
csrf:
  enable_check: true
  target: "http://localhost:8000/"

---

spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    hibernate:
      ddl-auto: create-drop
