---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
csrf:
  enable_check: true
  target: "http://localhost:8000/"

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/java_meetup_test
  jpa:
    hibernate:
      ddl-auto: create-drop
