---

spring:
  datasource:
    url: "jdbc:h2:file:./db"
  jpa:
    hibernate:
      ddl-auto: create
csrf:
  enable_check: true
  target: "http://localhost/"

---

spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:testdb"
  jpa:
    hibernate:
      ddl-auto: create-drop
